name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID: $NETLIFY_SITE_ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Project
        run: deno task build

      - name: Install Netlify CLI
        run: deno add npm:netlify-cli@latest

      - name: Link to the corresponding Netlify site
        run: netlify link --token $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=dist
